// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {hardware} from '../models';
import {process} from '../models';
import {optimizer} from '../models';

export function CleanTempFiles():Promise<number>;

export function FlushDNS():Promise<boolean>;

export function GetActivePowerPlan():Promise<string>;

export function GetDrives():Promise<Array<hardware.DriveItem>>;

export function GetProcesses():Promise<Array<process.ProcessItem>>;

export function GetStartupItems():Promise<Array<optimizer.StartupItem>>;

export function GetTelemetry():Promise<hardware.TelemetrySnapshot>;

export function HideWindow():Promise<void>;

export function IsGameBoostActive():Promise<boolean>;

export function IsTimerActive():Promise<boolean>;

export function KillProcess(arg1:number):Promise<boolean>;

export function OptimizeInputLatency():Promise<boolean>;

export function PurgeStandbyRAM():Promise<number>;

export function SetAlwaysOnTop(arg1:boolean):Promise<void>;

export function SetHudMode(arg1:boolean):Promise<void>;

export function SetPowerPlan(arg1:string):Promise<boolean>;

export function ShowWindow():Promise<void>;

export function SnapHudPosition(arg1:string):Promise<void>;

export function ToggleGameBoost(arg1:boolean):Promise<optimizer.GameBoostResult>;

export function ToggleHighPrecisionTimer(arg1:boolean):Promise<boolean>;

export function ToggleStartupItem(arg1:string,arg2:string,arg3:boolean):Promise<boolean>;
