// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanTempFiles() {
  return window['go']['main']['App']['CleanTempFiles']();
}

export function FlushDNS() {
  return window['go']['main']['App']['FlushDNS']();
}

export function GetActivePowerPlan() {
  return window['go']['main']['App']['GetActivePowerPlan']();
}

export function GetDrives() {
  return window['go']['main']['App']['GetDrives']();
}

export function GetProcesses() {
  return window['go']['main']['App']['GetProcesses']();
}

export function GetTelemetry() {
  return window['go']['main']['App']['GetTelemetry']();
}

export function KillProcess(arg1) {
  return window['go']['main']['App']['KillProcess'](arg1);
}

export function SetPowerPlan(arg1) {
  return window['go']['main']['App']['SetPowerPlan'](arg1);
}
