// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanTempFiles() {
  return window['go']['main']['App']['CleanTempFiles']();
}

export function FlushDNS() {
  return window['go']['main']['App']['FlushDNS']();
}

export function GetActivePowerPlan() {
  return window['go']['main']['App']['GetActivePowerPlan']();
}

export function GetDrives() {
  return window['go']['main']['App']['GetDrives']();
}

export function GetProcesses() {
  return window['go']['main']['App']['GetProcesses']();
}

export function GetTelemetry() {
  return window['go']['main']['App']['GetTelemetry']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function IsGameBoostActive() {
  return window['go']['main']['App']['IsGameBoostActive']();
}

export function IsTimerActive() {
  return window['go']['main']['App']['IsTimerActive']();
}

export function KillProcess(arg1) {
  return window['go']['main']['App']['KillProcess'](arg1);
}

export function OptimizeInputLatency() {
  return window['go']['main']['App']['OptimizeInputLatency']();
}

export function PurgeStandbyRAM() {
  return window['go']['main']['App']['PurgeStandbyRAM']();
}

export function SetPowerPlan(arg1) {
  return window['go']['main']['App']['SetPowerPlan'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function ToggleGameBoost(arg1) {
  return window['go']['main']['App']['ToggleGameBoost'](arg1);
}

export function ToggleHighPrecisionTimer(arg1) {
  return window['go']['main']['App']['ToggleHighPrecisionTimer'](arg1);
}
